### ISSUE TITLE
GraphiQL App hides Query Variables Section

### ISSUE THREAD

**Issue by Kphillycat** [Shopify/shopify-demo-app-node-react#104]
# Bug summary

The Shopify GraphiQL App doesn't fully show the Query Variables Section making it tough to follow along with the GraphQL sandbox portion of the tutorial https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/learn-the-graphql-admin-api#play-in-the-sandbox

## Expected behavior

What do you think should happen?
Query Variables Section should be visible

## Actual behavior

What actually happens?
Query Variables Section is hidden 

## Steps to reproduce the problem

1. Install Shopify GraphiQL App according to the instructions in the tutorial https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/learn-the-graphql-admin-api#play-in-the-sandbox
2. Try to perform the mutation from the tutorial
3. Query Variables Section does not exist

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

Add more the height on the Query Variable section (this is how I actually got it to work see the screenshot below) or create some type of overflow scroll so we can scroll down to the section. Also, the store transfer flash message at the bottom might also be causing the section to hide.

<img width="1207" alt="Screen Shot 2020-01-02 at 11 50 50 AM" src="https://user-images.githubusercontent.com/663277/71683269-17586200-2d60-11ea-9453-4bc9f851ad44.png">

## Specifications

- Browser: Chrome
- Device: Mac Book Air
- Operating System: OS X

**Comment by gfscott** [comment]
Hey @Kphillycat, thanks for getting in touch! GraphiQL usually lets you drag the frames to the size you want — you should be able to enlarge the "query variable" pane by clicking and dragging up the border:

This is the behavior it _should_ offer (it's a big GIF file, might take a second to load):
![Screen Recording 2020-01-02 at 16 23 15](https://user-images.githubusercontent.com/547470/71694409-200b6100-2d7d-11ea-8f86-c1351aab4058.gif)

If it’s not actually allowing you to do this, or the "query variables" section is totally absent, then we'll have to look into it further.

**Comment by Kphillycat** [comment]
@gfscott Thanks so much for getting back to me so quickly! Yes, I see the Query Variable section now and can drag to enlarge it. We good 👍
