### ISSUE TITLE
Toast component causes error on save

### ISSUE THREAD

**Issue by LeaderOne** [Shopify/shopify-demo-app-node-react#109]
The sample project's save functionality from the tutorial displays a Toast component when a product's discount is saved:  

```
const showToast = data && data.productVariantUpdate && (
     <Toast
          content="Sucessfully updated" onDismiss={() => this.setState({ showToast: false })}
      />
);
```

However, when the Toast component attempts to render after a successful save, an error appears in the console and the screen turns blank:
```
The above error occurred in the <Toast> component:
    in Toast (created by Mutation)
    in div (created by Layout)
    in Layout (created by Mutation)
    in div (created by Page)
    in div (created by Page)
    in Page (created by WithAppProvider(Page))
    in WithAppProvider(Page) (created by Mutation)
    in Mutation (created by EditProduct)
    in EditProduct (created by MyApp)
    in ApolloProvider (created by MyApp)
    in MediaQueryProvider (created by AppProvider)
    in div (created by ThemeProvider)
    in ThemeProvider (created by AppProvider)
    in AppProvider (created by MyApp)
    in Provider (created by MyApp)
    in MyApp
    in Suspense

React will try to recreate this component tree from scratch using the error boundary you provided, MyApp.
```
No "above error" is seen in the console, so there seems to be no clue how to fix this.

**Comment by katiedavis** [comment]
hi @LeaderOne sorry for the delay!

It looks like there was an update to Polaris that is causing this issue. The toast component now requires the 'frame' component:  https://polaris.shopify.com/components/structure/frame#navigation

If you wrap your <Page> in edit-products.js in the <Frame> and import it from Polaris this will work. I'll be updating the tutorial to reflect this shortly! Thank you for bringing this to our attention :)
