### ISSUE TITLE
Example for protected routes which require some initial app onboarding

### ISSUE THREAD

**Issue by uri3000** [Shopify/shopify-demo-app-node-react#11]
# Issue summary

I am using this example from the React + Apollo + Next tutorial and I cannot figure out how to implement a behaviour which redirects the user to onboarding if he hasn't gone through onboarding yet.

## Expected behavior

What do you think should happen?

1. A user opens my app on Shopify
2. If the user has already gone through onboarding then continue to the Dashboard.
3. If the user hasn't gone through onboarding, send his to the onboarding page.
4. This logic should run for every page in the system and it should work on server as well as on client.

## Actual behavior

This is not included in the example tutorial

@gfscott @katiedavis  Just a general note, as someone with decent experience building products and API's, you guys are moving really quickly and replacing the recommended technology all the time. That's fine, however, when you do it without providing a real production ready example, it causes a huge investment of time from developers like me who are trying to build apps the way you recommend.

In the case of this example: 

- You did not include a recommended way to include an additional Apollo server for our own API, I suppose this is very common scenario.

- Since our app is going to serve multiple stores, we need a way to identify each store in our systems. It could have been helpful to include this in the example as well (what id should we be using - is shopOrigin enough? not sure...)

- Passing parameters to pages, this is very basic need for almost every app developed.

- The motivation behind using Next.js was not explained - this is usually used for SEO considerations or when you need performance improvements in a very large scale maybe. Not clear.

- How about providing an example for a fully pledges app? IMO using just React without Next.js should do the trick and be enough for 99% of developers. 

This was just a general note. 
Looking forward to your reply, thanks.

**Comment by nwtn** [comment]
Hi @uri3000. First, thanks for the feedback about pace of change for our developer products. We’re aware this hasn’t been a super smooth experience in the past, and it’s something we’re working to do better at. I’ll share your feedback with the relevant teams.

For the redirection question, from your use case I’d suggest adding a middleware into the koa server to handle the onboarding check and redirection. It would be similar to how auth is handled. [This medium post](https://medium.com/netscape/mastrering-koa-middleware-f0af6d327a69) has a good overview of middleware in koa, including how it compares to express (if that’s something you’re more familiar with).

For now, this is out of scope of what we want to cover in the tutorial, but I’ll take your suggestions back to the team for planning future iterations. In the meantime, you may have some luck getting help from our support staff or other partners by posting this question in our [API & SDK Community forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).

**Comment by uri3000** [comment]
Hi @nwtn, thanks a lot for taking the time to read what I sent and reply.

To my understanding, koa middleware would handle the redirect only on the server. Since you're recommending to use next.js it means there are 2 entry points now for every page - one from the server and another one from a pure client side navigation. This means that some protected routes would be easily "hacked" by navigating on the client side, am I correct? 

Regarding leaving it out of the scope of the tutorial - its too bad since these challenges are for sure going to be a real pain for every developer starting to work on a new Shopify app using this tutorial. These are not issues specific to my case in any way and I am pretty sure that if you provide more thorough examples it would eventually increase the number of apps in the Shopify app store. Obviously that's your call I am just here to give you my feedback, I really suggest you guys to talk with more developers who are going through the same tutorial and look into this.

Regarding API & SDK Community Forums - unfortunately they have not replied to my questions. 

Out of good will to help the community, I would happily share my own project once we have all those issues sorted out. If you are interested please let me know. 

Thanks!

**Comment by uri3000** [comment]
Any help with the question I sent on my last point would be very appreciated...
isn't koa middleware meant for server side only? what happens if the react app navigates on client side? If I'm not mistaking you solution won't work in that scenario, will it?
Thanks

**Comment by nwtn** [comment]
Good question about what happens when navigating on the client-side. This isn’t something I’ve personally tested, and I’m not actually sure if the middleware would get hit in this case. I suspect not, unless Next.js is doing something fancy to handle this; that said, you should test it out to make sure.

The middleware would definitely be hit on initial load (when the user navigates to the app) or any time there is a hard refresh of the app. If that’s not the appropriate time to do this check for your use case, you’ll likely have to build in some client-side functionality that either checks for an appropriate cookie/session, makes a call back to the server to perform a check, or forces a reload/hard nav.
