### ISSUE TITLE
Trying to update my app to support samesite cookie update by Feb 4th

### ISSUE THREAD

**Issue by ranjitatwal30** [Shopify/shopify-demo-app-node-react#129]
Got multiple reminders from Shopify to update my apps, if I'm using  "koa-shopify-auth" library for embedded app.

https://help.shopify.com/en/api/guides/samesite-cookies

I did give it a try, by updating koa-shopify-auth, and then add this code "app.use(session({ secure: true, sameSite: 'none' }, app))" after "server.use(session(server));" , but received an error:

(node:1872) UnhandledPromiseRejectionWarning: TypeError: app instance required: `session(opts, app)`

Anybody got an idea on how to correctly do it ?

**Comment by katiedavis** [comment]
Hi @ranjitatwal30!

I am about to update our resources for this change, but in the context of this app you need to pass `server` not `app` to your call.

IE:
`  server.use(session({ secure: true, sameSite: 'none' }, server))`

`app` is the next.js app instance and server is the node server :)

I will be updating shortly though!

**Comment by KevinM818** [comment]
Using a Mongo collection to store app sessions. 

`
const session = require('koa-session');
const MongooseStore = require('koa-session-mongoose');
const connection = await mongoose.connect(process.env.MONGODB_URI, {useNewUrlParser: true,useUnifiedTopology: true});

server.use(session({
      secure: true,
      sameSite: 'none',
      store: new MongooseStore({
        collection: 'appSessions',
        connection,
        expires: 86400,
        name: 'AppSession'
      }) 
    }, server));
`

When I added the secure and sameSite properties to the session I got the following error:
`Error: Cannot send secure cookie over unencrypted connection`

My app is hosted on a https connection, anyone have an idea of what could be going wrong?

**Comment by ranjitatwal30** [comment]
Yes, getting same error while using code : "server.use(session({ secure: true, sameSite: 'none' }, server));"

Error: Cannot send secure cookie over unencrypted connection. Although I'm using ngrok tunnel for secure connection.

**Comment by katiedavis** [comment]
Hello! We're working out a solution on our end and I'll let you know when it's updated :)

**Comment by ranjitatwal30** [comment]
Thanks @katiedavis , appreciate the update.

**Comment by katiedavis** [comment]
Hey @ranjitatwal30 & KevinM818 !

As an update, we are making a small change to the shopify-koa-auth package to support the cookies being set to secure, which will eliminate your error. I'll let you know when the package is released and you can update.

Also, Chrome changed the date for sameSite cookies to Feb 17th :) So you have some time.

**Comment by KevinM818** [comment]
Awesome, thanks for the update @katiedavis

**Comment by katiedavis** [comment]
Okay! Please run npm update and make sure your koa-shopify-auth package is at 3.1.56

If you have any questions about what to update in your server or how to handle your own cookies you can follow this pr on our node app here:
https://github.com/Shopify/shopify-app-node/pull/209

**Comment by ranjitatwal30** [comment]
Ok, so I updated the packages and updated code as per this commit: https://github.com/Shopify/shopify-demo-app-node-react/pull/144/commits/6fb8b0aa4499926088ce3cdbc3e21a43499f4e38

Good thing, not getting any error like earlier, but still I can see this error in my console:

A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.

I tried fetching "shopOrigin" to link "Back to Shopify", but the value returned is undefined.

**Comment by katiedavis** [comment]
You will still see a lot of errors for samesite cookies in your console, a lot of them are set by shopify libraries and other things. 

I'm not sure what you mean by 'I tried fetching "shopOrigin" to link "Back to Shopify", but the value returned is undefined.' ?

https://help.shopify.com/en/api/guides/samesite-cookies if you follow this guide at the bottom you'll see how to set flags on your browser to ensure the app is working

**Comment by ranjitatwal30** [comment]
Sorry, got it working. By the way I was referring to this code:

```ctx.cookies.set("shopOrigin", shop, {
            httpOnly: false,
            secure: true,
            sameSite: 'none'
          });```

added this code like this as well:

```server.use(async (ctx, next) => {


    const { shop, accessToken } = ctx.session;

    if(!ctx.cookies.get("shopOrigin")){

      ctx.cookies.set("shopOrigin", shop, {
        httpOnly: false,
        secure: true,
        sameSite: 'none'
      });

    }
 
    await next();
});```
