### ISSUE TITLE
something wrong with koa-shopify-auth with next.js

### ISSUE THREAD

**Issue by alsguimaraes** [Shopify/shopify-demo-app-node-react#14]
Basic test should allow to verify that the problem exists. 
The solution might be trickier... 
I don't have a clue, as I am new to some of these technologies.

1) Bring up the application, and access localhost:3000/auth?shop=blablah, and get a 404 error.
2) Bring up the application, and access localhost:3000/?shop=blablah, and get the app page.

It seems like koa-shopify-auth is not running.

**Comment by tylerball** [comment]
Hi @alsguimaraes, let's continue our discussion in your original issue #12.
