### ISSUE TITLE
Shopify Next.js + React demo getInitialProps runs only on server on all pages

### ISSUE THREAD

**Issue by uri3000** [Shopify/shopify-demo-app-node-react#15]
# Issue summary

I am writing a public Shopify app based on your example of Apollo, Next.js, Node toolset.
I have a forced onboarding flow on the app, which means that as long as a user hasn't gone through onboarding, all app pages will redirect him to the onboarding page.

This is implemented as followed and it works:

`import { Component } from 'react';
import redirectTo from '../utils/redirect-to';

// Gets the display name of a JSX component for dev tools
const getDisplayName = c => c.displayName || c.name || 'Component';

export const withSetupRedirect = WrappedComponent => class extends Component {
    static displayName = `(${getDisplayName(WrappedComponent)})`

    static async getInitialProps(ctx) {
        console.log('withSetupRedirect getInitialProps');

        const componentProps = WrappedComponent.getInitialProps
            && (await WrappedComponent.getInitialProps(ctx));

        // redirection logic happens here
        return { ...componentProps };
    }

    render() {
        return <WrappedComponent {...this.props} />;
    }
};
`

Since it is Next.js here, I would like to test my redirection logic both on Server side as well as on the Client, however, I cannot reproduce a scenario which executes getInitialProps on the Client side.

Here is why I tried:

1. User which hasn't gone through onboarding navigates manually to https://{shop}/{myapp}/campaigns Page which is wrapped  with withSetupRedirect(...)

2. User gets redirected as expected to the onboarding page.

3. Now on the onboarding page, user presses on a Polaris <Line> which navigates back to https://{shop}/{myapp}/campaigns. 

## Expected behavior

I should see the log line "withSetupRedirect getInitialProps" at least once on the client side (browser console) and not only on the server side logs (npm terminal).

## Actual behavior

I only see the log line "withSetupRedirect getInitialProps" executing on the server side (npm terminal). 

## Steps to reproduce the problem

1. Just create a few pages based on the app example from this repo
2. Inside each page create a getInitialProps function which write a log line
3. Add <Link> navigation between the pages
4. Run the app and navigate randomly between pages while also using the browser Back and Forward buttons.
5. You should see that as opposed to what you would expect, the log line from step (2) is written only on the server side. 

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chrome
- Device: MacBook Pro

**Comment by liamgriffin** [comment]
Thanks for opening this issue @uri3000 & for including a comprehensive description of what you are looking to achieve. Our partner tooling team will look this asap and try to determine what is causing this.

**Comment by katiedavis** [comment]
Hey @uri3000, this seems like an issue that might be more appropriate for the next/zeit forums. 

According to the [docs](https://github.com/zeit/next.js/#fetching-data-and-component-lifecycle): 
```getInitialProps will only be executed on the client when navigating to a different route via the Link component or using the routing APIs.```

Because your code is outside of the scope of our tutorial, it's hard for me to run it and debug, but I hope you can find support for this method.

**Comment by uri3000** [comment]
@katiedavis I did navigate using the Link component. 
See my initial posting and search for this text "Now on the onboarding page, user presses on a Polaris Link component which navigates back to https://{shop}/{myapp}/campaigns".
According to the docs, as you yourself said, pressing on the Link component should trigger a client render and the log line which I mentioned should be fired on the client, but it doesn't.
As a result, I am not sure it is out of scope - please re-open, thanks.

**Comment by katiedavis** [comment]
@uri3000 I think the confusion here is that you're using a "Polaris link" component, when you need to use the [link](https://github.com/zeit/next.js/#with-link-1) component from Next. Hope this helps :)

**Comment by uri3000** [comment]
Hi Katie, so you are saying that if I use the polaris link it will not
support the client side render?
The tutorial is using next.js, so if I use only Polaris components it will
always render from the server.

I hope its ok to ask but what are the advantages of using Next.js for a
shopify app?
I am just trying to understand the logic behind this and decide wether I
should just remove Next.js from the tutorial skeleton and revert to simple
React CSR.
Thanks
