### ISSUE TITLE
Is there any possibility of the certain KOA router without shopify auth 

### ISSUE THREAD

**Issue by Kcin1993** [Shopify/shopify-demo-app-node-react#17]
# Issue summary
I want to use a KOA router which won't use koa-shopify-auth and won't redirect to Shopify admin panel.

When I browser site(e.g `https://abcdef.ngrok.io/customers`) in an incognito window, it won't redirect to Shopify admin. But there is some resource can't get and make website crack. (Screenshot below)

## Expected behavior
Here is my server.js file. Add koa router `/customers` for everyone view this site directly. And I create `customer.js` file in my next project's `pages` folder.

**Is there any way that I can create the router which can be viewed directly by users? Appreciate for the example code snippet!** 

```
require("isomorphic-fetch");

const { default: createShopifyAuth } = require("@shopify/koa-shopify-auth");
const { verifyRequest } = require("@shopify/koa-shopify-auth");
const { default: graphQLProxy } = require("@shopify/koa-shopify-graphql-proxy");

const Koa = require("koa");
const Router = require("koa-router");
const next = require("next");
const session = require("koa-session");
const dotenv = require("dotenv");
const axios = require("axios");

dotenv.config();

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

const { SHOPIFY_API_KEY, SHOPIFY_API_SECRET_KEY } = process.env;

app.prepare().then(() => {
  const server = new Koa();
  const router = new Router();
  server.use(session(server));
  server.keys = [SHOPIFY_API_SECRET_KEY];

  server.use(
    createShopifyAuth({
      apiKey: SHOPIFY_API_KEY,
      secret: SHOPIFY_API_SECRET_KEY,
      accessMode: "offline",
      scopes: [
        "read_product_listings",
        "write_product_listings",
        "read_products",
        "read_orders",
        "write_orders",
        "read_checkouts",
        "write_checkouts",
        "read_customers"
      ],
      async afterAuth(ctx) {
        const { shop, accessToken } = ctx.session;
        //... do something to keep shop and accessToken
      }
    })
  );

  /**GraphQL Admin API  */
  server.use(graphQLProxy());

  /**For everyone can view direct */
  router.get("/customers", async (ctx, next) => {
    console.log(`[Info] customers. Path: ${ctx.url}`);
    await app.render(ctx.req, ctx.res, "/customers");
    ctx.respond = false;
    ctx.res.statusCode = 200;
  });

  router.get("*", verifyRequest(), async ctx => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
    ctx.res.statusCode = 200;
    return;
  });

  server.use(router.allowedMethods());
  server.use(router.routes());

  server.listen(port, () => {
    console.log("> Server run on port " + port);
  });
});

```

<img width="1440" alt="螢幕快照 2019-05-16 下午4 52 36" src="https://user-images.githubusercontent.com/8435927/57840463-3c14bf00-77fb-11e9-9ba6-6d0add276495.png">

## Specifications

- Browser: Google Chrome 73.0.3683.103
- Device: MacBook Air 2018
- Operating System: macOS Mojave

**Comment by Kcin1993** [comment]
Here are two key points and what I thought:

* `verifyRequest()` in server.js
*  the component `<AppProvider />` in _app.js

---

### verifyRequest()

In doc's [explanation](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify)

```
The verifyRequest redirects users to the OAuth route if they haven’t been authenticated. 
```

I think that is why some resources are 400 bad requests. Because they haven't been authorized.

### AppProvider component

`forceRedirect` will redirect page to admin with `shopOrigin` url. 

---

### Solution

Here is my solution. I'm not sure it is best or not.

**1.Remove verifyRequest()**

Remove verifyRequest() in server.js

**2.Conditional forceRedirect**

Check the current is the public page or not. If true just return <AppProvider /> with `forceRedirect` equal false.

```jsx
// in _app.js file. Focus on AppProvider, ignore other

<div>
  {this.state.isClientsPages ? (
    <AppProvider forceRedirect={false}>
      <Component {...pageProps} />
    </AppProvider>
  ) : (
    <AppProvider
      shopOrigin={this.state.shopId}
      apiKey={SHOPIFY_API_KEY}
      forceRedirect={true}
    >
      <ApolloProvider client={client}>
        <Component {...pageProps} />
      </ApolloProvider>
    </AppProvider>
  )}
</div>
```

Thus it can't public view certain page without redirect to admin or auth. 
Appreciate for any adivce~

**Comment by katiedavis** [comment]
Hi @Kcin1993, I think what you're saying is you'd like to show routes outside of the Shopify iframe, is that right? This tutorial sets you up to make an embedded app. The AppProvider, which is at the top level of the client side of this application is specifically looking for a shopOrigin, so if you're outside of the iframe it will probably cause a lot of errors. If you're looking to create an app that doesn't exist inside of the Shopify iframe you may need to consult the partner forums for tips!

**Comment by katiedavis** [comment]
I should mention that if conditionally forceRedirecting is working for your purposes, there's nothing wrong with it.

**Comment by Kcin1993** [comment]
@katiedavis Thanks for your reply.

Our app is embedded app but only one path, we want it can be accessed by those who have the URL. Not only Shopify store owner but also certain customers might reach this path.

We are keeping to observe this situation. If there was some issue we will consider removing this public path from our Shopfiy App and host it to another web host.

**Comment by sunnyrvtech** [comment]
Hey , i have just followed the above conversation and i have also the similar situation.I want to add proxy url route that i will access from store front end like https://shop_name/apps/proxy_route.

When i access this from frontend it is redirected to auth route .

Thanks

**Comment by Kcin1993** [comment]
Hi @sunnyrvtech 

Now we solve this situation just like [the comment above](https://github.com/Shopify/shopify-demo-app-node-react/issues/17#issuecomment-493432871).

Remove the `verifyRequest()` in server.js and add some condition to the `<AppProvider />` component's forceRedirect props.

Hope that can help u

**Comment by sunnyrvtech** [comment]
Hi @Kcin1993 

Thanks for your quick reply.
I don't think to remove verifyRequest() is a good idea .Is there any way ,if we can add verifyRequest() with some routes and avoid this for third party route.

**Comment by Kcin1993** [comment]
@sunnyrvtech 

If keeping the `verifyRequest()` in server.js, some resource of next js can't get from the browser because they don't be auth. 

It still can be rendered with plain HTML but I think that is a bad development experience.

Although I remove the `verifyRequest()` but I wrap an appAuthChecker component in the key admin panel page. This makes sure when the store owner operates within the admin panel, my app can get full auth with Shopify store.

In my appAuthChecker component, it will check the storeOrigin and accessToken is available from the cookie and also run the GraphQL admin API request with these data to make sure that my app can work with GraphQL admin API. If not I will ask the store owner to enter the store name again and reinstall App again.

Totally I think this situation still need the Shopify's support. For a better solution.

I'm glad you notice = )

**Comment by Kcin1993** [comment]
@sunnyrvtech 

Another way might be that using `koa-router` and adding `verifyRequest()` for each router of the admin panel.

**Comment by sunnyrvtech** [comment]
Hi @Kcin1993 

Any example of koa-router with verifyRequest() ...    i am not sure how to add next js route with  koa-router.

**Comment by Kcin1993** [comment]
@sunnyrvtech 

I haven't use koa-router way to solve this need. It just a thought and I'm still not familiar with koa-router. Thus I might not be able to help.

**Comment by Kcin1993** [comment]
@sunnyrvtech  This might be work

Verify all request. Just like the tutorial
```
//...ignore
server.use(verifyRequest());
```

Verify the certain router. Use verifyRequest() in router's middleware
```
const Router = require("koa-router");
const router = new Router();
//...ignore

    router.get("/", verifyRequest()); 
    router.get("/a", verifyRequest());
    router.get("/b", verifyRequest());
    router.get("/c", verifyRequest());
    router.get("/d", verifyRequest());

    server.use(router.routes()).use(router.allowedMethods());
```

The a, b, c, d is the pages folder of your next.js project.
