### ISSUE TITLE
Reinstallation Bug

### ISSUE THREAD

**Issue by chadhamre** [Shopify/shopify-demo-app-node-react#22]
# Bug summary

I built an app with a server identical to the tutorial. Yet once deployed Shopify testers cannot re-install the app after uninstalling it. 

https://screenshot.click/03-26-rt1xs-ahxve.mp4

That said, I cannot reproduce it by re-installing with the link: 
https://find-replace.herokuapp.com/auth?shop=XXXXXXX.myshopify.com. 
The bug only seems to affect them when the use their internal "install app" button.

## Expected behavior

App should easily reinstall.

## Actual behavior

https://screenshot.click/03-26-rt1xs-ahxve.mp4

## Steps to reproduce the problem

1. Please ask Shea from the App Testing Team.

## Specifications

- Browser: Chrome Incognito

**Comment by chadhamre** [comment]
`require("isomorphic-fetch");
const Koa = require("koa");
const next = require("next");
const { default: createShopifyAuth } = require("@shopify/koa-shopify-auth");
const dotenv = require("dotenv");
const { verifyRequest } = require("@shopify/koa-shopify-auth");
const session = require("koa-session");

dotenv.config();
const logger = require("koa-logger");
const { default: graphQLProxy } = require("@shopify/koa-shopify-graphql-proxy");
const Router = require("koa-router");
const {
  receiveWebhook,
  registerWebhook
} = require("@shopify/koa-shopify-webhooks");
const processPayment = require("./server/router");

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

const {
  SHOPIFY_API_SECRET_KEY,
  SHOPIFY_API_KEY,
  TUNNEL_URL,
  API_VERSION
} = process.env;

app.prepare().then(() => {
  const server = new Koa();
  const router = new Router();
  server.use(logger());
  server.use(session(server));
  server.keys = [SHOPIFY_API_SECRET_KEY];

  router.get("/", processPayment);

  server.use(
    createShopifyAuth({
      apiKey: SHOPIFY_API_KEY,
      secret: SHOPIFY_API_SECRET_KEY,
      scopes: ["read_products", "write_products"],
      async afterAuth(ctx) {
        const { shop, accessToken } = ctx.session;
        ctx.cookies.set("shopOrigin", shop, { httpOnly: false });
        const stringifiedBillingParams = JSON.stringify({
          recurring_application_charge: {
            name: "Recurring charge",
            price: 1.99,
            return_url: TUNNEL_URL
          }
        });

        const options = {
          method: "POST",
          body: stringifiedBillingParams,
          credentials: "include",
          headers: {
            "X-Shopify-Access-Token": accessToken,
            "Content-Type": "application/json"
          }
        };
        const confirmationURL = await fetch(
          `https://${shop}/admin/api/2019-04/recurring_application_charges.json`,
          options
        )
          .then(response => response.json())
          .then(
            jsonData => jsonData.recurring_application_charge.confirmation_url
          )
          .catch(error => console.log("error", error));
        ctx.redirect(confirmationURL);
      }
    })
  );

  const webhook = receiveWebhook({ secret: SHOPIFY_API_SECRET_KEY });

  router.post("/webhooks/redact", webhook, ctx => {
    console.log("received webhook: ", ctx.state.webhook);
  });

  server.use(graphQLProxy());
  router.get("*", verifyRequest(), async ctx => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
    ctx.res.statusCode = 200;
  });
  server.use(router.allowedMethods());
  server.use(router.routes());

  server.listen(port, () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
});
`

**Comment by katiedavis** [comment]
@chadhamre There could be an issue with the installation button. This tutorial provides the URL for installation, so that's how users can install the app on their shop for testing and QA purposes. 

Any issues with QA or support are outside of scope of the tutorial, hopefully Shopify Support can help you out with this one!

**Comment by chadhamre** [comment]
Is there really no way you can take a quick look at this for me? Surely the goal of this tutorial is to lead people to production apps, and without access to 'the button' I can't replicate.

**Comment by tylerball** [comment]
Hi Chad, is it the "install on development store" button you're referencing? or something else? 
![image](https://user-images.githubusercontent.com/73874/58651907-66c54400-82e0-11e9-967e-cea2f654a714.png)

**Comment by chadhamre** [comment]
I'm not exactly sure, it's whatever members of the app QA team use to install apps onto test stores. I'll send them a note to find out.

**Comment by chadhamre** [comment]
Wohoo! Thanks @tylerball I can replicate the bug! I had not been using that button for installation, I'd been just using the direct link: https://find-replace.herokuapp.com/auth?shop=XXXXXXX.myshopify.com. Now that I can re-produce, surely I can hunt down the issue. Thanks!

**Comment by chadhamre** [comment]
Alright, I think I've got it. It looks like it's an issue with cookies. When I selectively ignore the incoming request cookies for a koa:session, then I can achieve reliable reinstallation. Perhaps there is a problem with the @shopify/koa-shopify-auth code repo? This is the little piece of middleware I used to make it work, ugly I now.

```
server.use(async (ctx, next) => {
    if (ctx.request.header.cookie) {
      if (
        (ctx.request.url.split("?")[0] === "/" &&
          ctx.request.querystring.split("&") &&
          ctx.request.querystring.split("&")[0].split("=")[0] === "hmac" &&
          ctx.request.querystring.split("&")[1].split("=")[0] !== "locale") ||
        (ctx.request.url.split("?")[0] === "/auth/callback" &&
          ctx.request.querystring.split("&") &&
          ctx.request.querystring.split("&")[1].split("=")[0] === "hmac")
      ) {
        {
          console.log("DROP COOKIES", ctx.request.url);
          ctx.request.header.cookie = ctx.request.header.cookie
            .split(" ")
            .filter(
              item =>
                ["koa:sess", "koa:sess.sig"].indexOf(item.split("=")[0]) === -1
            )
            .join(" ");
        }
      }
    }
    await next();
  });
```

**Comment by Popesites** [comment]
This should be added to the repository. I was going mad wondering why it would redirect me to the ngrok port after reinstalling.

**Comment by chadhamre** [comment]
@Popesites please leave feedback on the new issue I opened for this bug. https://github.com/Shopify/quilt/issues/727
