### ISSUE TITLE
Instruction to build production

### ISSUE THREAD

**Issue by RezaRahmati** [Shopify/shopify-demo-app-node-react#24]
Hi

It would be very useful if you add some documents about how to build prod and deploy the app

For example to firebase hosting or any other hostings

Thanks

**Comment by katiedavis** [comment]
Hi @RezaRahmati Thanks for this suggestion! Closing this for now, but we will consider feature requests in our roadmap planning.

**Comment by JacksonChristopherHowell** [comment]
bump
