### ISSUE TITLE
Deprecation: Using `apiKey` and `shopOrigin` on `AppProvider` 

### ISSUE THREAD

**Issue by EchelonEric** [Shopify/shopify-demo-app-node-react#28]
# Bug summary

While following the tutorial, using the app displays the following deprecation warnings in console:

<details> Deprecation: Using `apiKey` and `shopOrigin` on `AppProvider` to initialize the Shopify App Bridge is deprecated. Support for this will be removed in v5.0. Use `Provider` from `@shopify/app-bridge-react` instead. For example, `import {Provider} from '@shopify/app-bridge-react';`</details>

## Expected behavior

Is it possible to get the tutorial updated or provide a solution?

## Actual behavior

What actually happens? There's some mention about this here [Should App Bridge be removed from Polaris?](https://github.com/Shopify/polaris-react/issues/814#issuecomment-493249756)

## Steps to reproduce the problem

1. Follow the [tutorial](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/)
2. Run the app

## Specifications

- Browser: Any
- Device: node.js
- Operating System: Mac OSX

**Comment by tim-phillips** [comment]
This is just a warning saying that the `AppProvider` component is moving to the `@shopify/app-bridge-react` package. It's not worded particularly well, which is pretty standard when it comes to Shopify. You can either ignore it or start using the new library.

**Comment by sunnyrvtech** [comment]
Hi @tim-phillips  

I have just used the new library i.e @shopify/app-bridge-react  and getting this error
AppBridgeError {name: "AppBridgeError", message: "APP::ERROR::INVALID_OPTIONS: Missing required `app`", action: undefined, type: "APP::ERROR::INVALID_OPTIONS", stack: "AppBridgeError: APP::ERROR::INVALID_OPTIONS: Missing required `app`"}

**Comment by tim-phillips** [comment]
Ah well maybe it's not ready for primetime. You can safely revert back to using `AppProvider` from the polaris library and ignore the warning.

**Comment by katiedavis** [comment]
Hi @sunnyrvtech and @tim-phillips! That warning is nothing to be too concerned about, Tim is right, App-Bridge has a new react library. https://github.com/Shopify/app-bridge/blob/master/packages/app-bridge-react/README.md

If you'd like to see an example of it implemented in a similar app, please see this _app file:
https://github.com/Shopify/shopify-app-node/blob/master/pages/_app.js

We will add plans to update the guide in our roadmap planning. Closing this for now.
