### ISSUE TITLE
write EPIPE error

### ISSUE THREAD

**Issue by tim-phillips** [Shopify/shopify-demo-app-node-react#29]
# Bug summary

When I run `npm run dev`, it compiles successfully but shows this error:
```
Error: write EPIPE
      at _errnoException (util.js:1022:11)
      at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
```

## Expected behavior

No error message

## Actual behavior

EPIPE error

<details>
Error: write EPIPE
      at _errnoException (util.js:1022:11)
      at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
</details>

## Steps to reproduce the problem

1. `git clone git@github.com:Shopify/shopify-demo-app-node-react`
2. create `.env` file
3. `npm install`
4. `npm run dev`

## Reduced test case

This lib reproduces.

## Specifications

- Browser: Chrome 74
- Device: Desktop
- Operating System: macOS 10.13.6

**Comment by katiedavis** [comment]
Hi @tim-phillips I've recently made some changes to the repo. Let me know if you're still experiencing this.
