### ISSUE TITLE
@koa-shopify-auth doesn't start authentication

### ISSUE THREAD

**Issue by keiraarts** [Shopify/shopify-demo-app-node-react#32]
# Bug summary

Write a short description of the bug here ↓

The app works perfectly on a local development environment via ngrok - but throws a 404 errors, graphQL unexpected token < in JSON at position 0, and never authenticates when deployed to an aliased domain via ZEIT Now.

## Expected behavior

The app should run and authenticate identically on a domain name as it does locally.

## Actual behavior

If deployed to ZEIT, the authentication URL would look like this.

https://shopify.viaglamour.com/auth?shop=via-staging2.myshopify.com

Opening this URL throws a 404 error. The @shopify/koa-shopify-auth is meant to recognize the /auth and begin the process of authentication but never does.

If I set the app's URL (and all the whitelisted URLS) back to my ngrok environment.

https://c6108518.ngrok.io/auth?shop=via-staging2.myshopify.com

The authentication screen is triggered and the app runs successfully!

Demo: https://gyazo.com/78e3a16fef817e73551895670eebaa5a

## Steps to reproduce the problem

1. Deploy the app to ZEIT.
1. Change local environment variables (like TUNNEL_URL) to the deployed ZEIT domain.
1. Attempt to authenticate via the URL

**Comment by katiedavis** [comment]
Hi @keiraarts! Are you using the 'build' command at any point to deploy? We haven't built out that command for the tutorial, and I'm pretty sure it doesn't pick up the custom server on build.

The guide doesn't cover deploying at the moment, but I have a feeling that the issue you're having is because npm run build builds the front end of the app.
Because this has a custom server, you'll need to modify the build command.
I found this on the next forums:
https://spectrum.chat/next-js/general/custom-server-in-production~81cd6879-9d7f-41b8-be3f-f69d86214d33
You'll probably want to write a small script that includes 'NODE_ENV=production node server.js

I'm going to add a feature-request tag to this as we've had a couple people asking about building for production :)

**Comment by keiraarts** [comment]
Hiya Katie!

I am using the build command, though I'm starting to doubt my deployments haha.

Are there any repositories available that show a deployed demo app (that authenticates) at Shopify? 

I'd love to reverse-engineer something to find my mistake.

**Comment by katiedavis** [comment]
Hey @keira! There aren't at the moment that I know of. 

I'm going to try to work on something as a demo, but I can't promise how quickly I can get it out. I do think the spectrum forums and issues on zeit/next.js can help in the meantime though. You need to make sure you create a build, and that when you deploy (I believe Zeit uses the start command) you're running a production version of the node server. I will ping you for sure when I have something ready, but I understand you want to get this app out there. 

It looks like this might help too: https://github.com/Shopify/shopify-demo-app-node-react/issues/9

**Comment by keiraarts** [comment]
I got progress @katiedavis!

The /auth is now being recognized after setting the production server. I also had to change the now.json configuration to include the environment variables. 

"build": {
    "env": {
      "SHOPIFY_API_KEY": "--",
      "SHOPIFY_API_SECRET_KEY": "--"
    }
  }

There's one last issue. I know I'm asking a lot - but maybe you've seen it before!

When visiting /auth on a production environment (and using the full domain on the app setup) the console throws this error.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://via-staging2.myshopify.com') does not match the recipient window's origin ('https://shopify.viaglamour.com').

I can recreate the error on a local environment if the origin URL != the URL in app setup.

But in a production environment the console ALWAYS throws this error regardless if the app setup's, environment variables, or now.json configuration matches the requested URL. It's happening on my own project and a cloned version of this tutorial.

GIF Demo: https://gyazo.com/cc337c362806f70c7eb5368f0a8a7f12

If you have any suggestions (like before!) it might help me get this app finished!

Otherwise I'm eagerly awaiting a deployed demo to pick apart. 

Thanks for your generous help Katie!

**Comment by keiraarts** [comment]
Consider the issue closed! @katiedavis 

This entire time I was deploying with Zeit's now that is _serverless_. 

My Koa _server_ was never going to work to authenticate there. 

I changed my deployment to Heroku and the issue is resolved. 

The fun of learning development! Thanks again for pushing me in the right direction.

**Comment by katiedavis** [comment]
Hey @keiraarts I'm so glad you got it sorted :) all the best.
