### ISSUE TITLE
Saving the configuration

### ISSUE THREAD

**Issue by bien119** [Shopify/shopify-demo-app-node-react#34]
Hi team,

How can I save the Discount percentage field?
![image](https://user-images.githubusercontent.com/39391418/61265659-64994500-a7bb-11e9-8a37-11f4128b26d1.png)
Where should I store them? How? and which technology should be used?

Thank you.

**Comment by tanema** [comment]
Hey @bien119 thanks for opening this however this issue board is not for general support, it is for  issues for bug reports about existing tutorial content. You can seek further support in our community forums: https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology
