### ISSUE TITLE
Uninstall and re-install app does not work

### ISSUE THREAD

**Issue by uri3000** [Shopify/shopify-demo-app-node-react#39]
When I run the following scenario, it does not work:
1. Install app on a new dev store
2. Use it successfully
3. Uninstall the app
4. Re-install it from partners dashboard

EXPECTED RESULT is that the app goes to auth screen and installs successfully.
ACTUAL RESULT is that the app fails to install due to the accessToken being available in the ctx.session and thus verifyRequest middleware passes validation.

The problem is that I do not have a way to know when I should redirect the user to the /auth URL (and re-authenticate the app).

What is the best practice to achieve the EXPECTED RESULT in this scenario?

**Comment by tanema** [comment]
Hey @uri3000 it seems like this is related to this issue here: https://github.com/Shopify/quilt/issues/727 feel free to pop over there and add a 👍 to the issue.

**Comment by katiedavis** [comment]
Hey this issue was fixed with the latest release of the koa-shopify-auth package. If you still run into issues please update the package :)
