### ISSUE TITLE
shopOrigin cookie not set outside of auth

### ISSUE THREAD

**Issue by lopert** [Shopify/shopify-demo-app-node-react#40]
# Bug summary
[During the tutorial](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-shopify-app-bridge), we add the shopOrigin cookie to the `createShopifyAuth` call with
`ctx.cookies.set('shopOrigin', shop, { httpOnly: false });`

However, this is only run during the initial auth. At this stage of the tutorial, the app has already been installed, and so this cookie never gets a chance to actually be set.

Once we attempt to actually use this cookie later in the tutorial, this leads to a `message: "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"` error in the console, and a blank page, when attempting to access the app in the admin.

## Expected behavior
The page should still load once app bridge is added. 
aka, the cookie should be set without having to go through the auth flow.

## Actual behavior
Gif: https://screenshot.click/2019-07-25_09-31-31_q5471-5zg7n.gif

## Steps to reproduce the problem
1. Get to step 4 of [Build your user interface with polaris](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-shopify-app-bridge)
2. Try to load your app within Shopify.

## Reduced test case
1. Take the end state of this tutorial step, available under the [starter files](https://github.com/Shopify/shopify-demo-app-node-react/tree/charge-a-fee-using-the-billing-api-starter-files)
2. Comment out the `ctx.cookies.set('shopOrigin', shop, { httpOnly: false });` line.
3. Run the app, installing it on your store.
4. Uncomment the ``ctx.cookies.set('shopOrigin', shop, { httpOnly: false });` line.
5. Stop/Start your server as per step 5 of [Build your user interface with polaris](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-shopify-app-bridge)
6. Attempt to open your app.

## Specifications

- Browser: Google Chrome 75
- Device: MacBook Pro
- Operating System: macOS Mojave 10.14.3

**Comment by katiedavis** [comment]
Added a note about re-installation. Thanks!

**Comment by miclovich** [comment]
Where was the note placed?

**Comment by miclovich** [comment]
@katiedavis where was the note about reinstallation placed?

**Comment by katiedavis** [comment]
@miclovich in the tutorial this repo accompanies. If you follow the link in this issue you should be able to find it!

**Comment by lopert** [comment]
@miclovich It has been added right under the "Restart your server" instructions.

![](https://screenshot.click/2019-07-29_08-47-10_ie0tq-3lcmz.png)

**Comment by dimanyc** [comment]
I am still getting the same error. It seems like `shop=...` query param is ignored. Is is possible that query params are not available in `ctx.session` ?

server.js:
```es6
      afterAuth(ctx) {
        const { shop, accessToken } = ctx.session
        ctx.cookies.set("shopOrigin", shop, { httpOnly: false })
        ctx.redirect("/")
      },
```
MyApp.jsx
```jsx
    const config = {
      apiKey: API_KEY,
      shopOrigin: Cookies.get("shopOrigin"), // returns `{}`
      forceRedirect: true,
    }
```
installation url:
```
https://[my subdomain].ngrok.io/auth?shop=[my store name].myshopify.com
```
returns:
```es6
AppBridgeError {
  name: "AppBridgeError", 
  message: "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided", 
  action: undefined, type: "APP::ERROR::INVALID_CONFIG", 
  stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"
 }```

**Comment by noctivityinc** [comment]
@dimanyc did you ever figure this out?  Same thing here in Chrome and Safari.
