### ISSUE TITLE
Missing Require Statement in Billing Section

### ISSUE THREAD

**Issue by ilee** [Shopify/shopify-demo-app-node-react#48]
# Bug summary
Missing require statement for getSubscriptionUrl on https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/charge-a-fee-using-the-billing-api
<img width="626" alt="Screen Shot 2019-08-19 at 15 24 52" src="https://user-images.githubusercontent.com/11542751/63303724-83489b00-c295-11e9-9bc1-ea545e791b83.png">

## Expected behavior
Server shouldn't bomb out when adding the test app back to the dev store after adding the billing functionality.

## Actual behavior
Server throws a `ReferenceError: getSubscriptionUrl is not defined` error when attempting to add the 
<img width="644" alt="Screen Shot 2019-08-19 at 15 20 03" src="https://user-images.githubusercontent.com/11542751/63303530-f7367380-c294-11e9-9acb-a1291ddff574.png">
because server.js doesn't have a way to reference the newly added `getSubscriptionUrl`

## Specifications
- Browser: Chrome 76
- Device: Macbook Pro
- Operating System: OS10

**Comment by ilee** [comment]
Fixed it by adding a require statement to `server.js`:
`const getSubscriptionUrl = require('./server/getSubscriptionUrl');`

**Comment by katiedavis** [comment]
Thanks for opening this issue @ilee! I've fixed in the documentation repo :)
