### ISSUE TITLE
After added to App to a Store; The page Shows 'Internal Server Error.

### ISSUE THREAD

**Issue by dydc** [Shopify/shopify-demo-app-node-react#50]
# Bug summary

Write a short description of the bug here ↓

After added to App to a Store; The page Shows 'Internal Server Error.

## Expected behavior

What do you think should happen?

The sample page should be seen.

## Actual behavior

What actually happens?

Folloing is the error from terminal:
[ error ] TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
[ event ] disposing inactive page(s): /, /next/dist/pages/_error
/.next/server/static/development/pages/_app.js:23:31

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser:
- Device:
- Operating System:

**Comment by katiedavis** [comment]
hey @dydc can you provide a bit more information? Did you start an ngrok tunnel and go through the steps for embedding your app? before you installed it in your shop did you have any errors or were you able to see the hello world text in your browser before adding the authentication step in your server?
