### ISSUE TITLE
API Version in registerWebhook

### ISSUE THREAD

**Issue by fischerjack** [Shopify/shopify-demo-app-node-react#53]
# Bug summary

Write a short description of the bug here ↓
I was having a heck of a time getting the webhook to register. My error logs showed that a fetch failed because my api version in the url was undefined. Perhaps it used to be default in the old @shopify/koa-shopify-webhooks package, but I checked today and the example registerWebhook shows that the object passed to it should include an apiVersion key-value pair.

## Expected behavior

What do you think should happen?
Tutorial did not put apiVersion key-value pair in the registerWebhook parameter object.
I expected it to work as shown in the tutorial. 

## Actual behavior

What actually happens?
It did not work until I read the @shopify/koa-shopify-webhooks npm package examples and found that an apiVersion key-value pair was needed. I added the apiVersion and it worked.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Follow tutorial. registerWebhook fails.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chromium
- Device: Lenovo Thinkpad x220
- Operating System: Ubuntu

**Comment by katiedavis** [comment]
Hi @fischerjack thank you so much for opening this issue. I have a PR pending translations in the correct repo waiting to go out!

**Comment by fischerjack** [comment]
Thank you for fixing this so quickly
