### ISSUE TITLE
Empty screen after saving product discount

### ISSUE THREAD

**Issue by gustavo807** [Shopify/shopify-demo-app-node-react#56]
#21 Bug summary

After saving the product discount, it throws an error in the browser console.
![image](https://user-images.githubusercontent.com/15847964/66596449-8740bd00-eb62-11e9-94c6-65b8d1e30a21.png)

## Expected behavior

The Toast message is display

## Actual behavior

It's display an empty sreen
![image](https://user-images.githubusercontent.com/15847964/66596295-3df06d80-eb62-11e9-9153-75fc9d373968.png)

## Steps to reproduce the problem

1. Add a product discount
2. Click Save

**Comment by jgray7019** [comment]
Hi @gustavo807, this is a tricky one to debug! I'd take another look at the tutorial (perhaps [here](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/fetch-data-with-apollo#set-up-mutation)) and double check that no steps were missed.

I'll be closing this for now as it does not appear to be an issue with this repo but if you do have more questions like this, the best place to ask them would be in the [Shopify Community](https://community.shopify.com) forums.
