### ISSUE TITLE
App fails.  Constantly reloads and warns about third party cookies

### ISSUE THREAD

**Issue by noctivityinc** [Shopify/shopify-demo-app-node-react#57]
# Bug summary

I created a FRESH app and a FRESH project and followed this tutorial exactly.

https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify

After authenticating the app with my sample store, I get redirected over and over again back to the page which shows "Sample app using React and Next.js" without it ever being embedded in the shopify admin.  I've tried it all the way up to the point after you add the App Bridge.

No matter what I do (log in, log out, check to see if Chrome or Safari accept third party cookies, etc), it always happens.  I even tried creating a new app to test it with the same result.

Here is the message Shopify eventually displays:

`The application can’t be loaded, check that your browser allows third-party cookies`

## Expected behavior

Index page is displayed within the Shopify Admin.

## Actual behavior

Continually redirecting between my server and the shopify admin until I see the error message in the Shopify Admin that says:

`The application can’t be loaded, check that your browser allows third-party cookies`

## Steps to reproduce the problem

1. Create a new fresh app from the partner dashboard
1. Follow the tutorial until the end of this part - https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris
1. Same result each time.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- Device: Macbook Pro
- Operating System: OSX Catalina

**Comment by noctivityinc** [comment]
![Screen Shot 2019-10-28 at 4 32 42 PM](https://user-images.githubusercontent.com/78850/67716264-db8ccf00-f9a1-11e9-8b80-e3af91353bf7.png)

**Comment by katiedavis** [comment]
Hi @noctivityinc. I'm so sorry about this issue!

I tried running the app off master and installed it on some shops with no issues. This seems to be a bug related to your cookies, but not specifically to this app.

I did find some open issues on the forum:
https://community.shopify.com/c/Shopify-APIs-SDKs/The-app-can-t-be-loaded-check-that-your-browser-allows-third/td-p/511861

https://community.shopify.com/c/Shopify-APIs-SDKs/How-to-fix-quot-The-application-cannot-be-loaded-please-check/m-p/176931

I know that it's probably not a scopes access issue, but perhaps the forums can be of use to you.

**Comment by noctivityinc** [comment]
@katiedavis - are you using the latest version of everything?  Did you do a fresh install of the packages?

I just tried it AGAIN using Firebox, Safari, Chrome and Chrome in ingonito with the same result.

Also, I just downloaded and created an app using the Shopify App CLI and the SAME thing happened.

Take a look at what we see in Firefox, which we also see in Safari:

![Screen Shot 2019-10-28 at 5 28 25 PM](https://user-images.githubusercontent.com/78850/67719622-8ef8c200-f9a8-11e9-9fde-708712626ad1.png)

**Comment by noctivityinc** [comment]
@katiedavis the error seems to be coming from the @shopify/app-bridge package:

```MessageTransport.js:85 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://pbp-demo-crafts.myshopify.com') does not match ```

I would post to that repo but that repo is not on github.

**Comment by katiedavis** [comment]
Hi @noctivityinc. I did use fresh versions of each package, thanks. I went through the tutorial step by step. I'm wondering if you're not passing the config to the app provider? 
see this step: https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-shopify-app-bridge

You should also throw a console.log in your `_app.js` file with the shopOrigin (you're getting it from cookies in this case ( Cookies.get("shopOrigin")) and see what shows up there.

**Comment by noctivityinc** [comment]
I literally cloned the repo and entered the config values into the .env
file - that's it.  Still the same error.

When I do a console log on getting the shopOrigin in _app.js it IS
undefined.  I think this relates to the postMessage or something else with
one of the Shopify packages.

**Comment by katiedavis** [comment]
Okay just to be clear are  you using master of this repository? or, are you are you following the repository and you're at the end of the `https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris` section?

**Comment by katiedavis** [comment]
It is not an issue with the package. The app bridge package needs the shopOrigin to initialize. Without it, it will fail.

**Comment by noctivityinc** [comment]
Give me a minute and I will repeat the entire thing and document it for you.

**Comment by noctivityinc** [comment]
@katiedavis sorry for the delay.  I wanted to record a video for you so you can see exactly what Im seeing.  I tried it twice to be sure and got the same both times.  It's just under 5 minutes:

https://www.screencast.com/t/Jx919kuzb

Let me know your thoughts.

**Comment by katiedavis** [comment]
Thanks for the video. This redirection loop is def strange, but not related to that step of the tutorial that you listed in this issue. I was under the impression this was happening when you created a new app and tried to add app bridge. Your shopOrigin key will always come back as undefined when you're outside of the iframe, and you will always get that app bridge error you're seeing whenever you're outside of the iframe. 

The redirect looks like it's based on something within the `billing` section of the tutorial. I'll take a look at that when I have a chance, in the meantime if you get stuck feel free to reach out in the Shopify Forums. I appreciate you taking the time to make this video!

**Comment by noctivityinc** [comment]
Katie-

I AM stuck, as you can see in the video.  There is NOTHING more we can do
given we are literally using Shopify provided code and having this redirect
error.  It is not on our site but something to do with the code.

Please let us know when fixed.

Best,

Josh

**Comment by katiedavis** [comment]
Hey Josh,

I ran the code in the exact same manner from master, with no issues. I even went as far as to delete the repository from my machine and delete the app and reinstall it four times. The only difference I can see between what you're doing and what we do on our ends is your ngrok account. Can you try using a free version of the tunnel and see if that corrects the redirect?

**Comment by noctivityinc** [comment]
@katiedavis something is definitely up.  I've now tried this out in Safari and Chrome on this computer, and then went onto a different Chromebook and tried and got the same result.    I even tried creating a NEW dev store in the partner dashboard and installing there with the same result.

Everything still seems to point to this error:

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').`

Which comes from app-bridge.  I can provide you with my package-lock.json if that would help to see if we have different versions of something but nothing works.

I also tried using `localtunnel` instead of ngrok to test out that theory - nothing.  From the forums I am DEFINITELY not the only person seeing this behavior.  Right now I might have to develop this in Ruby since this code is broken.

**Comment by noctivityinc** [comment]
@katiedavis good morning.  

OK, I have more info for you.  This does not appear to be related directly to my app (or your repo).

I just tried to use the Google and Facebook apps that Shopify provides for marketing and has the SAME thing happen in Chrome!  Here is the URL:

https://facebook-ads.shopifycloud.com/top_level_interaction?shop=fruitstand-com.myshopify.com

Some of my apps worked, some didnt.  Im guessing the ones built with a specific package are the problematic ones where others are not.

I'm guessing this issue is related to the latest version of Chrome.  When I try it in Safari, I get multiple messages about needing to enable third party cookies from the Shopify packages but it eventually works.

Hopefully you can escalate this internally as whatever is going on is effecting multiple apps and it's definitely related to some Shopify package that we don't have access to.

**Comment by katiedavis** [comment]
Hi @noctivityinc Thanks for the update! There is something that seems very unique and strange that's happening on your end, we will investigate internally, but I'm very sure it has nothing to do with this tutorial.

I'm sorry you're experiencing this issue.

**Comment by dommmel** [comment]
Seeing this as well. Could this be linked to https://github.com/Shopify/quilt/issues/1099 ?

**Comment by noctivityinc** [comment]
I noticed that by completely removing and reinstalling Chrome I was able to
stop the redirects.

**Comment by dommmel** [comment]
> I noticed that by completely removing and reinstalling Chrome I was able to stop the redirects.

I am seeing this on Safari 13 on Mac OS

**Comment by tylerball** [comment]
@dommmel what Mac OS version are you using?

**Comment by dommmel** [comment]
> @dommmel what Mac OS version are you using?

macOS 10.15.1 (19B88)

**Comment by dommmel** [comment]
Updating the npm packages seems to have solved the problem for me. 

```diff
-    "koa": "^2.8.2",
-    "@shopify/app-bridge": "^1.6.8",
-    "@shopify/app-bridge-react": "^1.6.8",
-    "@shopify/koa-shopify-auth": "^3.1.42",
-    "@shopify/koa-shopify-graphql-proxy": "^3.1.2",
+    "koa": "^2.11.0",
+    "@shopify/app-bridge": "^1.11.0",
+    "@shopify/app-bridge-react": "^1.11.0",
+    "@shopify/koa-shopify-auth": "^3.1.49",
+    "@shopify/koa-shopify-graphql-proxy": "^3.2.1",
```

Sorry, should have tried that first. Might be worth to update the package.json of this repo to not receive issues from people like me ;-)
