### ISSUE TITLE
Latest version of repo fails to register webhook.

### ISSUE THREAD

**Issue by noctivityinc** [Shopify/shopify-demo-app-node-react#59]
# Bug summary

Cloned repo.  Added key, secret and host and ran to authenticate.  Ends up looping back to request for payment due to failure to register the webhook.

Also, the repo now requires a HOST env yet there is no description of what this is in the repo README.

Also, almost NONE of the links in the README work.

## Expected behavior

Webhook should register and app would proceed.

## Actual behavior

App redirects back to request for payment.  Console shows this error:

Failed to register webhook { data:
   { webhookSubscriptionCreate: { userErrors: [Array], webhookSubscription: null } },
  extensions:
   { cost:
      { requestedQueryCost: 10,
        actualQueryCost: 10,
        throttleStatus: [Object] } } }

## Steps to reproduce the problem

1. Clone repo.
1. Add keys and ngrok host
1. Run `npm run dev`
1. Authenticate app
1. Accept payment prompt

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
- Device: Macbook Pro
- Operating System: OSX Catalina

**Comment by noctivityinc** [comment]
This seems to be the same bug as before dealing with postMessage.  I'm guessing that one of the Shopify repos was updated that introduced this bug recently:

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').`

**Comment by katiedavis** [comment]
Hi @noctivityinc here is a link to the tutorial that this repo was created for that tells you to add your ngrok tunnel to the `env file` as your host:
https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/charge-a-fee-using-the-billing-api#set-up

**Comment by katiedavis** [comment]
I'll dig into the webhook registration and take a look at what is going on.

**Comment by noctivityinc** [comment]
You should probably update the repo read me as well and fix all the broken
links.

**Comment by katiedavis** [comment]
hey @noctivityinc thanks for the feedback! that's already been done :)

**Comment by noctivityinc** [comment]
Ok. I should tell you I tried the node example and while it doesn’t end up
integrating bridge it did display embedded in the admin without the
redirect so something in your version is causing the redirect. I believe
it’s the postMessage associated with app bridge. Since the repost are gone
on GitHub I could not investigate.

**Comment by katiedavis** [comment]
I believe this is related to something very specific about your setup. I just cloned the repository and have no issues with webhook registration:
<img width="835" alt="Screen Shot 2019-10-29 at 12 39 11 PM" src="https://user-images.githubusercontent.com/15366319/67788805-56f58b80-fa49-11e9-9686-b71b455e15a2.png">

I'm going to close this and continue corresponding with you on your other issue.
