### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by 521lixin** [Shopify/shopify-demo-app-node-react#65]
In the original terminal window, this appears when the server is started
![微信截图_20191113162046](https://user-images.githubusercontent.com/45504555/68745578-d7afac80-0631-11ea-9406-0e80d4a80f13.png)

Adding the HTTPS version of the ngrok forward URL and the store's URL to the following placeholder and loading it into the browser also presents a problem,
![22_20191113162541](https://user-images.githubusercontent.com/45504555/68745820-5573b800-0632-11ea-812f-6c670592de56.png)
Can you help me out？

**Comment by osamaeshtiaq** [comment]
Have you started your NGROK server on port 3000?

**Comment by katiedavis** [comment]
Hello, you're missing the auth
`/auth?shop=makelikej.myshopify.com`
I'm going to close this issue also because it's very stale.
