### ISSUE TITLE
Deploy shopify app to heroku

### ISSUE THREAD

**Issue by Kcin1993** [Shopify/shopify-demo-app-node-react#9]
# Issue summary
We use NGROK in development mode. I had deployed the app to Heroku and has some issue as following. 

Is there any advice for this [stack](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react)(Next, Koa) deploying to production? 

## Expected behavior
 
I can redirect between pages, **both are the pages in my App** by using `@shopify/polaris`component and `shopify/app-bridge`.

## Actual behavior

When I click the button in my app and try to redirect to another page in my app, error comes up in browser console.

```
uncaught exception: AppBridgeError: APP::ERROR::INVALID_OPTIONS: Missing required `app`
```

I know `@shopify/app-bridge` is used in `@shopify/polaris` and I use them as [tutorial way](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/fetch-data-with-apollo#set-up-mutation) to redirect my page. 

```
// ...
import { Page } from "@shopify/polaris";
import { Redirect } from "@shopify/app-bridge/actions";
import * as PropTypes from "prop-types";


class Groups extends React.Component {
  static contextTypes = {
    polaris: PropTypes.object
  };
  redirectToGroupCreate = () => {
    const redirect = Redirect.create(this.context.polaris.appBridge);
    redirect.dispatch(Redirect.Action.APP, "/groupCreate");
  };
  return (
    <Page
      title="All groups"
      primaryAction={{
        content: "Create",
        onAction: () => this.redirectToGroupCreate()
      }}
    >
      // ...
    </Page>
  );
}
```

<img width="1432" alt="chrome" src="https://user-images.githubusercontent.com/8435927/56859040-b6e67900-69b7-11e9-8734-ba21120b4301.png">

Above image is the screen shot of the app which is deploy to Heroku. Do I miss something to redirect the page in my app? 

The button works fine in Ngrok. When I deploy to Heroku, it has issue above.

## Specifications

- Browser: Google Chrome 73.0.3683.103
- Device: MacBook Air 2018
- Operating System: macOS Mojave

**Comment by gfscott** [comment]
Hi @Kcin1993, thanks for filing an issue, and for including these details. We’re looking into it now!

**Comment by nwtn** [comment]
Hi @Kcin1993. This may happen if `this.context.polaris.appBridge` is null or otherwise invalid, which could be caused by a missing [Polaris AppProvider component](https://polaris.shopify.com/components/structure/app-provider). The different behaviour on local/ngrok vs heroku is surprising, though, I’m not sure what would cause that.

Since this is outside the scope of the tutorial and this repo, my suggestion would be to repost this question in our [Community APIs & SDKs forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for support.

**Comment by nwtn** [comment]
Also, thank you for the idea to add deploy into the scope of the tutorial. It’s something we’ll consider for future iterations

**Comment by Kcin1993** [comment]
Glad to see your reply and your direction. I will report back if I find the answer. It will help a lot if doc contains the section of deployment.

**Comment by robhemsley** [comment]
This behaviour is observed when building and running the tutorial in production mode. `npm run build && NODE_ENV=production npm run dev`

I'm not familiar with next but assume some magic during the build process.

**Comment by robhemsley** [comment]
@nwtn @Kcin1993 Looks like the env var `SHOPIFY_API_KEY` used in the [next.config.js](https://github.com/Shopify/shopify-demo-app-node-react/blob/master/next.config.js#L4) isn't loaded when `next build` is called. Needed to add the following to load the .env variables

```
const dotenv = require('dotenv');
dotenv.config();
```

**Comment by Kcin1993** [comment]
I don't go deep on deploying to Heroku. I try using AWS ELB which just like NGROK. 

Here is some note:

1. Make sure ELB has SSL. Shopify required https. If not, you might see `errors: "SSL Required"`. Using AWS ACM can easily setup SSL for ELB.
2. Build then deploy. Run `next build` --> `eb deploy`. 
3. The start script should like be `"start": "node server.js"` to run the server.js file of next.js project
4. Remember to update the `.env` on your ELB

**Comment by Kcin1993** [comment]
@robhemsley Thanks for your reply!
Nice viewpoint. It helps me a lot. 

For those who need:
Just add `dotenv` into your `next.config.js`. Add other env value if you need and I have use typescript for my next project. 

```
require("dotenv").config();

const withCSS = require("@zeit/next-css");
const webpack = require("webpack");
const withTypescript = require("@zeit/next-typescript");

module.exports = withTypescript(
  withCSS({
    webpack: config => {
      const env = {
        SHOPIFY_API_KEY: JSON.stringify(process.env.SHOPIFY_API_KEY),
        YOUR_OTHER_ENV: JSON.stringify(process.env.YOUR_OTHER_ENV)
      };
      config.plugins.push(new webpack.DefinePlugin(env));
      return config;
    }
  })
);

```

**Comment by JacksonChristopherHowell** [comment]
getting the same error, got the env variables in my next.config.js
